version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cinco_irmoes
      MYSQL_USER: system
      MYSQL_PASSWORD: system_pass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8082:80"
    environment:
      - PMA-HOST=db
      - PMA-USER=root
      - PMA-PASSWORD=root
      
  api:
    image: node:latest
    working_dir: /app
    container_name: api
    volumes:
      - ./api:/app
    ports:
      - "9090:9090"
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

  # frontend:
  #   image: node:latest
  #   working_dir: /app
  #   volumes:
  #     - ./frontend:/app 
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - api
  #   command: bash -c "npm install && npm run dev -- --host"

volumes:
  db_data: